export const COUNTRIES = [
  "Nigeria", "Ghana", "Kenya", "South Africa", "United States", "United Kingdom",
  "Canada", "Germany", "France", "Brazil", "India", "Japan", "Australia",
  "Singapore", "UAE", "Turkey", "Indonesia", "Philippines", "Mexico", "Colombia",
  "Argentina", "Egypt", "Morocco", "Tanzania", "Ethiopia", "Cameroon", "Senegal",
  "Rwanda", "Uganda", "Ivory Coast",
] as const;

export const CITIES: Record<string, string[]> = {
  Nigeria: ["Lagos", "Abuja", "Port Harcourt", "Ibadan", "Kano", "Benin City"],
  Ghana: ["Accra", "Kumasi", "Tamale", "Cape Coast"],
  Kenya: ["Nairobi", "Mombasa", "Kisumu", "Nakuru"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria"],
  "United States": ["New York", "Los Angeles", "Chicago", "Miami", "San Francisco", "Austin"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Edinburgh"],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary"],
  Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt"],
  France: ["Paris", "Lyon", "Marseille", "Toulouse"],
  Brazil: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"],
  India: ["Mumbai", "Delhi", "Bangalore", "Chennai"],
  Japan: ["Tokyo", "Osaka", "Kyoto", "Yokohama"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth"],
  Singapore: ["Singapore"],
  UAE: ["Dubai", "Abu Dhabi", "Sharjah"],
  Turkey: ["Istanbul", "Ankara", "Izmir"],
  Indonesia: ["Jakarta", "Bali", "Surabaya", "Bandung"],
  Philippines: ["Manila", "Cebu", "Davao"],
  Mexico: ["Mexico City", "Guadalajara", "Monterrey", "Cancún"],
  Colombia: ["Bogotá", "Medellín", "Cali", "Cartagena"],
  Argentina: ["Buenos Aires", "Córdoba", "Rosario"],
  Egypt: ["Cairo", "Alexandria", "Giza"],
  Morocco: ["Casablanca", "Marrakech", "Rabat", "Fez"],
  Tanzania: ["Dar es Salaam", "Dodoma", "Arusha"],
  Ethiopia: ["Addis Ababa", "Dire Dawa"],
  Cameroon: ["Douala", "Yaoundé", "Bamenda"],
  Senegal: ["Dakar", "Saint-Louis", "Thiès"],
  Rwanda: ["Kigali", "Butare"],
  Uganda: ["Kampala", "Entebbe", "Jinja"],
  "Ivory Coast": ["Abidjan", "Yamoussoukro", "Bouaké"],
};
