project_id = "wiahygtlhcqmmescchfa"

[functions.tapestry-identity]
verify_jwt = false

[functions.matchmaking]
verify_jwt = false

[functions.bot-gameplay]
verify_jwt = false

[functions.player-chat]
verify_jwt = false
